//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpToolsLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HpToolsLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find TestSet {0}.
        /// </summary>
        internal static string AlmRunnerCantFindTest {
            get {
                return ResourceManager.GetString("AlmRunnerCantFindTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the required connection parameters is empty..
        /// </summary>
        internal static string AlmRunnerConnParamEmpty {
            get {
                return ResourceManager.GetString("AlmRunnerConnParamEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link: {0}.
        /// </summary>
        internal static string AlmRunnerDisplayLink {
            get {
                return ResourceManager.GetString("AlmRunnerDisplayLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test set name: {0}, Test set id: {1}.
        /// </summary>
        internal static string AlmRunnerDisplayTest {
            get {
                return ResourceManager.GetString("AlmRunnerDisplayTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test {0}: {1} will run on host: {2}.
        /// </summary>
        internal static string AlmRunnerDisplayTestRunOnHost {
            get {
                return ResourceManager.GetString("AlmRunnerDisplayTestRunOnHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Login to QC: Authorization failed..
        /// </summary>
        internal static string AlmRunnerErrorAuthorization {
            get {
                return ResourceManager.GetString("AlmRunnerErrorAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that your QC client is installed properly\n {0} \n{1}..
        /// </summary>
        internal static string AlmRunnerErrorBadQcInstallation {
            get {
                return ResourceManager.GetString("AlmRunnerErrorBadQcInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to QC: Project / Domain does not exist..
        /// </summary>
        internal static string AlmRunnerErrorConnectToProj {
            get {
                return ResourceManager.GetString("AlmRunnerErrorConnectToProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem in updating tests status for test: {0}\n {1}.
        /// </summary>
        internal static string AlmRunnerErrorGettingStat {
            get {
                return ResourceManager.GetString("AlmRunnerErrorGettingStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder {0} cannot be found in ALM.
        /// </summary>
        internal static string AlmRunnerNoSuchFolder {
            get {
                return ResourceManager.GetString("AlmRunnerNoSuchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Number of tests in set: &quot;.
        /// </summary>
        internal static string AlmRunnerNumTests {
            get {
                return ResourceManager.GetString("AlmRunnerNumTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem while setting remote host: {0}.
        /// </summary>
        internal static string AlmRunnerProblemWithHost {
            get {
                return ResourceManager.GetString("AlmRunnerProblemWithHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem while running TestSet: .
        /// </summary>
        internal static string AlmRunnerRunError {
            get {
                return ResourceManager.GetString("AlmRunnerRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run ID:.
        /// </summary>
        internal static string AlmRunnerRunIdCaption {
            get {
                return ResourceManager.GetString("AlmRunnerRunIdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Scheduler started at:.
        /// </summary>
        internal static string AlmRunnerSchedStarted {
            get {
                return ResourceManager.GetString("AlmRunnerSchedStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ALM server {0} unreachable, check that server Url is correct&quot;.
        /// </summary>
        internal static string AlmRunnerServerUnreachable {
            get {
                return ResourceManager.GetString("AlmRunnerServerUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting test set execution.
        /// </summary>
        internal static string AlmRunnerStartingExecution {
            get {
                return ResourceManager.GetString("AlmRunnerStartingExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: {0}, Id: {1}, Execution status: {2}.
        /// </summary>
        internal static string AlmRunnerStat {
            get {
                return ResourceManager.GetString("AlmRunnerStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: {0}, Id: {1}, Execution status: {2}, Message: {3}.
        /// </summary>
        internal static string AlmRunnerStatWithMessage {
            get {
                return ResourceManager.GetString("AlmRunnerStatWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test complete:.
        /// </summary>
        internal static string AlmRunnerTestCompleteCaption {
            get {
                return ResourceManager.GetString("AlmRunnerTestCompleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test set: {0}, finished at {1}.
        /// </summary>
        internal static string AlmRunnerTestsetDone {
            get {
                return ResourceManager.GetString("AlmRunnerTestsetDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test: {0}, Status: {1}, Message: {2} \nLink: {3}\n.
        /// </summary>
        internal static string AlmRunnerTestStat {
            get {
                return ResourceManager.GetString("AlmRunnerTestStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete report folder {0}..
        /// </summary>
        internal static string CannotDeleteReportFolder {
            get {
                return ResourceManager.GetString("CannotDeleteReportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string DirectoryNotExistError {
            get {
                return ResourceManager.GetString("DirectoryNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception was thrown from external process..
        /// </summary>
        internal static string ExceptionExternalProcess {
            get {
                return ResourceManager.GetString("ExceptionExternalProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run cancelled by user..
        /// </summary>
        internal static string ExceptionUserCancelled {
            get {
                return ResourceManager.GetString("ExceptionUserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Temp Dir {0}..
        /// </summary>
        internal static string FailedToCreateTempDirError {
            get {
                return ResourceManager.GetString("FailedToCreateTempDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Micro Focus testing tool is installed on {0}.
        /// </summary>
        internal static string FileSystemTestsRunner_No_HP_testing_tool_is_installed_on {
            get {
                return ResourceManager.GetString("FileSystemTestsRunner_No_HP_testing_tool_is_installed_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===============================\nThere are no valid tests to run!\n===============================.
        /// </summary>
        internal static string FsRunnerNoValidTests {
            get {
                return ResourceManager.GetString("FsRunnerNoValidTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running test: {0}.
        /// </summary>
        internal static string FsRunnerRunningTest {
            get {
                return ResourceManager.GetString("FsRunnerRunningTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result: {0}.
        /// </summary>
        internal static string FsRunnerTestDone {
            get {
                return ResourceManager.GetString("FsRunnerTestDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result: Succeeded with Warnings.
        /// </summary>
        internal static string FsRunnerTestDoneWarnings {
            get {
                return ResourceManager.GetString("FsRunnerTestDoneWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tests found:.
        /// </summary>
        internal static string FsRunnerTestsFound {
            get {
                return ResourceManager.GetString("FsRunnerTestsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========================\nJob was aborted by user!\n========================.
        /// </summary>
        internal static string GeneralAbortedByUser {
            get {
                return ResourceManager.GetString("GeneralAbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ============================================================================.
        /// </summary>
        internal static string GeneralDoubleSeperator {
            get {
                return ResourceManager.GetString("GeneralDoubleSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Parameter {0} of test: {1} is defined more than once.
        /// </summary>
        internal static string GeneralDuplicateParameterWarning {
            get {
                return ResourceManager.GetString("GeneralDuplicateParameterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}\n{1}.
        /// </summary>
        internal static string GeneralErrorWithStack {
            get {
                return ResourceManager.GetString("GeneralErrorWithStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; File/Folder not found: {0}.
        /// </summary>
        internal static string GeneralFileNotFound {
            get {
                return ResourceManager.GetString("GeneralFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTP is not installed on {0}..
        /// </summary>
        internal static string GeneralQtpNotInstalled {
            get {
                return ResourceManager.GetString("GeneralQtpNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Started...&quot;.
        /// </summary>
        internal static string GeneralStarted {
            get {
                return ResourceManager.GetString("GeneralStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run was aborted by user. Stopping all tests..
        /// </summary>
        internal static string GeneralStopAborted {
            get {
                return ResourceManager.GetString("GeneralStopAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test run was cancelled.
        /// </summary>
        internal static string GeneralTestCanceled {
            get {
                return ResourceManager.GetString("GeneralTestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==============\nJob timed out!\n==============.
        /// </summary>
        internal static string GeneralTimedOut {
            get {
                return ResourceManager.GetString("GeneralTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout has expired.
        /// </summary>
        internal static string GeneralTimeoutExpired {
            get {
                return ResourceManager.GetString("GeneralTimeoutExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LoadRunner version must be 11.52 or higher. Check that &apos;{0}&apos; has a compatible version of LoadRunner..
        /// </summary>
        internal static string HPToolsAssemblyResolverWrongVersion {
            get {
                return ResourceManager.GetString("HPToolsAssemblyResolverWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid report path provided: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidReportPath {
            get {
                return ResourceManager.GetString("InvalidReportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run mode is set to: {0}.
        /// </summary>
        internal static string LauncherDisplayRunmode {
            get {
                return ResourceManager.GetString("LauncherDisplayRunmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run status: {0}, total tests: {1}, succeeded: {2}, failures: {3}, errors: {4}.
        /// </summary>
        internal static string LauncherDisplayStatistics {
            get {
                return ResourceManager.GetString("LauncherDisplayStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ================================================.
        /// </summary>
        internal static string LauncherDoubleSeperator {
            get {
                return ResourceManager.GetString("LauncherDoubleSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;runMode&apos; should be: RUN_LOCAL | RUN_REMOTE | RUN_PLANNED_HOST.
        /// </summary>
        internal static string LauncherIncorrectRunmode {
            get {
                return ResourceManager.GetString("LauncherIncorrectRunmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cleanup tests were found. Add some cleanup tests..
        /// </summary>
        internal static string LauncherNoCleanupTestsFound {
            get {
                return ResourceManager.GetString("LauncherNoCleanupTestsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No failed tests were found. Fix the test paths..
        /// </summary>
        internal static string LauncherNoFailedTestsFound {
            get {
                return ResourceManager.GetString("LauncherNoFailedTestsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results filename provided, please add one.
        /// </summary>
        internal static string LauncherNoResFilenameFound {
            get {
                return ResourceManager.GetString("LauncherNoResFilenameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No runType parameter was provided. Enter a runType (Alm/FileSystem/LoadRunner)..
        /// </summary>
        internal static string LauncherNoRuntype {
            get {
                return ResourceManager.GetString("LauncherNoRuntype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test sets were found. Add some test sets or folders..
        /// </summary>
        internal static string LauncherNoTests {
            get {
                return ResourceManager.GetString("LauncherNoTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tests were found. Add tests or folders containing tests..
        /// </summary>
        internal static string LauncherNoTestsFound {
            get {
                return ResourceManager.GetString("LauncherNoTestsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid cleanup tests were found. Fix the test paths..
        /// </summary>
        internal static string LauncherNoValidCleanupTests {
            get {
                return ResourceManager.GetString("LauncherNoValidCleanupTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid failed tests to rerun were found. Fix the test paths..
        /// </summary>
        internal static string LauncherNoValidFailedTests {
            get {
                return ResourceManager.GetString("LauncherNoValidFailedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid tests were found. Fix the test paths..
        /// </summary>
        internal static string LauncherNoValidTests {
            get {
                return ResourceManager.GetString("LauncherNoValidTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is required to run a test from QC..
        /// </summary>
        internal static string LauncherParamRequired {
            get {
                return ResourceManager.GetString("LauncherParamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while disposing runner: {0}..
        /// </summary>
        internal static string LauncherRunnerDisposeError {
            get {
                return ResourceManager.GetString("LauncherRunnerDisposeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Test is not installed on {0}.
        /// </summary>
        internal static string LauncherStNotInstalled {
            get {
                return ResourceManager.GetString("LauncherStNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to almTimeout should be an integer!.
        /// </summary>
        internal static string LauncherTimeoutNotNumeric {
            get {
                return ResourceManager.GetString("LauncherTimeoutNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadRunner is not installed on {0}..
        /// </summary>
        internal static string LoadRunnerNotInstalled {
            get {
                return ResourceManager.GetString("LoadRunnerNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing results....
        /// </summary>
        internal static string LrAnalysingResults {
            get {
                return ResourceManager.GetString("LrAnalysingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during Analysis run. See output console for details.
        /// </summary>
        internal static string LrAnalysisRunTimeError {
            get {
                return ResourceManager.GetString("LrAnalysisRunTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout for Analysis passed..
        /// </summary>
        internal static string LrAnalysisTimeOut {
            get {
                return ResourceManager.GetString("LrAnalysisTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Analysis launcher..
        /// </summary>
        internal static string LrAnlysisInitFail {
            get {
                return ResourceManager.GetString("LrAnlysisInitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Results:.
        /// </summary>
        internal static string LrAnlysisResults {
            get {
                return ResourceManager.GetString("LrAnlysisResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up the environment....
        /// </summary>
        internal static string LrCleanENV {
            get {
                return ResourceManager.GetString("LrCleanENV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller failed to stop..
        /// </summary>
        internal static string LrControllerFailedToStop {
            get {
                return ResourceManager.GetString("LrControllerFailedToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored error message : &quot;{0}&quot; contains ignored string &quot;{1}&quot;..
        /// </summary>
        internal static string LrErrorIgnored {
            get {
                return ResourceManager.GetString("LrErrorIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors during scenario run: \n.
        /// </summary>
        internal static string LRErrorReasonSummaryTitle {
            get {
                return ResourceManager.GetString("LRErrorReasonSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s) summary: .
        /// </summary>
        internal static string LRErrorsSummary {
            get {
                return ResourceManager.GetString("LRErrorsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ignored , {1} errors.
        /// </summary>
        internal static string LrErrorSummeryNum {
            get {
                return ResourceManager.GetString("LrErrorSummeryNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to analyze results:.
        /// </summary>
        internal static string LRExceptionInAnalysisRunner {
            get {
                return ResourceManager.GetString("LRExceptionInAnalysisRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open scenario {0} ret code = {1}..
        /// </summary>
        internal static string LrFailedToOpenScenario {
            get {
                return ResourceManager.GetString("LrFailedToOpenScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the LoadRunner Controller..
        /// </summary>
        internal static string LrFailToOpenController {
            get {
                return ResourceManager.GetString("LrFailToOpenController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register the end scenario event. End scenario detection is based on Vuser status..
        /// </summary>
        internal static string LrFailToRegisterEndScenarioEvent {
            get {
                return ResourceManager.GetString("LrFailToRegisterEndScenarioEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing scenario {0} for execution..
        /// </summary>
        internal static string LrInitScenario {
            get {
                return ResourceManager.GetString("LrInitScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during RTS in script {0}: {1}.
        /// </summary>
        internal static string LrRTSError {
            get {
                return ResourceManager.GetString("LrRTSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot collate results ret code = {0}..
        /// </summary>
        internal static string LrScenarioCollateFail {
            get {
                return ResourceManager.GetString("LrScenarioCollateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario {0} ended after {1}:{2}:{3}..
        /// </summary>
        internal static string LrScenarioEnded {
            get {
                return ResourceManager.GetString("LrScenarioEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout passed. Stopping scenario by force..
        /// </summary>
        internal static string LrScenarioEndedTimeOut {
            get {
                return ResourceManager.GetString("LrScenarioEndedTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred during scenario execution. Stopping the scenario run..
        /// </summary>
        internal static string LrScenarioEndedWithErrors {
            get {
                return ResourceManager.GetString("LrScenarioEndedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario open process timed out..
        /// </summary>
        internal static string LrScenarioOpenTimeOut {
            get {
                return ResourceManager.GetString("LrScenarioOpenTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Execution timeout {0} (d:h:m:s) passed..
        /// </summary>
        internal static string LrScenarioTimeOut {
            get {
                return ResourceManager.GetString("LrScenarioTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Load Generator {0}..
        /// </summary>
        internal static string LrScenarioValidationCannotConnectLG {
            get {
                return ResourceManager.GetString("LrScenarioValidationCannotConnectLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot synchronize with Load Generator {0}..
        /// </summary>
        internal static string LrScenarioValidationCannotSyncLG {
            get {
                return ResourceManager.GetString("LrScenarioValidationCannotSyncLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Load Generators were configured for the scenario {0.}.
        /// </summary>
        internal static string LrScenarioValidationFailNoLGs {
            get {
                return ResourceManager.GetString("LrScenarioValidationFailNoLGs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario {0}  does not have an SLA configuration..
        /// </summary>
        internal static string LrScenarioValidationFailNoSLA {
            get {
                return ResourceManager.GetString("LrScenarioValidationFailNoSLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Generator {0} connected.
        /// </summary>
        internal static string LrScenarioValidationLGConnected {
            get {
                return ResourceManager.GetString("LrScenarioValidationLGConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Load Generator {0}..
        /// </summary>
        internal static string LrScenarioValidationLGNotReady {
            get {
                return ResourceManager.GetString("LrScenarioValidationLGNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLA rule {0} failed: GoalValue = {1} ActualValue = {2}.
        /// </summary>
        internal static string LrSLARuleFailed {
            get {
                return ResourceManager.GetString("LrSLARuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting scenario....
        /// </summary>
        internal static string LrStartScenario {
            get {
                return ResourceManager.GetString("LrStartScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start scenario {0}. Return Code = {1}..
        /// </summary>
        internal static string LrStartScenarioFail {
            get {
                return ResourceManager.GetString("LrStartScenarioFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop scenario failed. Return code = {0}.
        /// </summary>
        internal static string LrStopScenarioEnded {
            get {
                return ResourceManager.GetString("LrStopScenarioEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during summary data logging: {0}.
        /// </summary>
        internal static string LrSummaryDataLoggingError {
            get {
                return ResourceManager.GetString("LrSummaryDataLoggingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test FAILED. {0} errors occurred during scenario execution..
        /// </summary>
        internal static string LRTestFailDueToFatalErrors {
            get {
                return ResourceManager.GetString("LRTestFailDueToFatalErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test PASSED.
        /// </summary>
        internal static string LRTestPassed {
            get {
                return ResourceManager.GetString("LRTestPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting test state to WARNING. {0} Ignored errors occurred during scenario execution..
        /// </summary>
        internal static string LRTestWarningDueToIgnoredErrors {
            get {
                return ResourceManager.GetString("LRTestWarningDueToIgnoredErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout is set to: {0}.
        /// </summary>
        internal static string LuancherDisplayTimout {
            get {
                return ResourceManager.GetString("LuancherDisplayTimout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ParallelRunnerExecutableNotFound {
            get {
                return ResourceManager.GetString("ParallelRunnerExecutableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTPActivity.TestCleanup - exception {0}.
        /// </summary>
        internal static string QtpCleanupError {
            get {
                return ResourceManager.GetString("QtpCleanupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTP is not launched..
        /// </summary>
        internal static string QtpNotLaunchedError {
            get {
                return ResourceManager.GetString("QtpNotLaunchedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTP could not handle output arguments..
        /// </summary>
        internal static string QtpOutputError {
            get {
                return ResourceManager.GetString("QtpOutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTP could not run..
        /// </summary>
        internal static string QtpRunError {
            get {
                return ResourceManager.GetString("QtpRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test execution stopped due to unsaved changes in QuickTest. 
        ///Save the test in QuickTest and then run it again..
        /// </summary>
        internal static string QtpUnsavedError {
            get {
                return ResourceManager.GetString("QtpUnsavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find results file &apos;{0}&apos;..
        /// </summary>
        internal static string ResultFileNotExistError {
            get {
                return ResourceManager.GetString("ResultFileNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------------------------------------------------.
        /// </summary>
        internal static string SingleSeperator {
            get {
                return ResourceManager.GetString("SingleSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===========================.
        /// </summary>
        internal static string SmallDoubleSeparator {
            get {
                return ResourceManager.GetString("SmallDoubleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro Focus Testing Tool is missing : Micro Focus Service Test/Micro Focus Unified Function Testing.
        /// </summary>
        internal static string STExecuterNotFound {
            get {
                return ResourceManager.GetString("STExecuterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UFT cannot start while the LeanFT engine is running..
        /// </summary>
        internal static string UFT_LeanFT_Running {
            get {
                return ResourceManager.GetString("UFT_LeanFT_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UFT cannot start while Micro Focus Sprinter is running..
        /// </summary>
        internal static string UFT_Sprinter_Running {
            get {
                return ResourceManager.GetString("UFT_Sprinter_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML node &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string XmlNodeNotExistError {
            get {
                return ResourceManager.GetString("XmlNodeNotExistError", resourceCulture);
            }
        }
    }
}
