/*
 * Certain versions of software and/or documents ("Material") accessible here may contain branding from
 * Hewlett-Packard Company (now HP Inc.) and Hewlett Packard Enterprise Company.  As of September 1, 2017,
 * the Material is now offered by Micro Focus, a separately owned and operated company.  Any reference to the HP
 * and Hewlett Packard Enterprise/HPE marks is historical in nature, and the HP and Hewlett Packard Enterprise/HPE
 * marks are the property of their respective owners.
 * __________________________________________________________________
 * MIT License
 *
 * (c) Copyright 2012-2021 Micro Focus or one of its affiliates.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * ___________________________________________________________________
 */

package com.microfocus.application.automation.tools.lr.model;

import com.microfocus.application.automation.tools.lr.Messages;
import hudson.Extension;
import hudson.model.AbstractDescribableImpl;
import hudson.model.Descriptor;
import hudson.EnvVars;
import org.kohsuke.stapler.DataBoundConstructor;
import org.apache.commons.lang.StringUtils;
import javax.annotation.Nonnull;
import java.util.List;
import java.util.Properties;

/**
 * The Controller's Api call requires the name of the script and an xml string which
 * will be generated by HpToolsLauncher based on the specified additional attributes
 */
public class ScriptRTSModel extends AbstractDescribableImpl<ScriptRTSModel> {
    private String scriptName;
    private List<AdditionalAttributeModel> additionalAttributes;
    static int additionalAttributeCounter = 1;

    @DataBoundConstructor
    public ScriptRTSModel(String scriptName, List<AdditionalAttributeModel> additionalAttributes) {
        this.scriptName = scriptName;
        this.additionalAttributes = additionalAttributes;
    }

    public List<AdditionalAttributeModel> getAdditionalAttributes() {
        return additionalAttributes;
    }

    public String getScriptName() {
        return scriptName;
    }


    /**
     * Adds additional attributes to the props file containing:
     * script name, additional attribute name, value and description
     *
     * @param props
     * @param scriptName
     */
    void addAdditionalAttributesToPropsFile(Properties props, String scriptName, EnvVars envVars)
    {
        for (AdditionalAttributeModel additionalAttribute: this.additionalAttributes) {
            if (!StringUtils.isEmpty(additionalAttribute.getName())) {
                props.put("AdditionalAttribute" + additionalAttributeCounter,
                    scriptName + ";"
                    + additionalAttribute.getName() + ";"
                    + envVars.expand(additionalAttribute.getValue()) + ";"
                    + additionalAttribute.getDescription()
                    );
                additionalAttributeCounter++;
            }
        }
    }

    @Extension
    public static class DescriptorImpl extends Descriptor<ScriptRTSModel> {
        @Nonnull
        public String getDisplayName() { return Messages.ScriptRTSModel(); }
    }
}
